### ISSUE TITLE
Add systemd services

### ISSUE THREAD

**Issue by lberrymage** [accrescent/devconsole#13]

**Comment by Tachi107** [comment]
I'd be happy to send a patch for this! Could you please give me some pointers?

**Comment by lberrymage** [comment]
Absolutely!

The service files should have strict hardening options. A good template to start with is [AttestationServer's systemd service](https://github.com/GrapheneOS/AttestationServer/blob/c14cca6200822eeac56639da9a38315644775d97/systemd/system/attestation.service). You can most likely add `MemoryDenyWriteExecute=true` to those options since we're not using Java. Further hardening options can be found with `systemd-analyze security`.

`WorkingDirectory` can be set to `/var/lib/devportal` and `/var/lib/reposerver` respectively. Neither `devportal` or `reposerver` need external network access since they're meant to be placed behind an nginx reverse proxy communicating over localhost.

Let me know if I can help with anything else.

**Comment by Tachi107** [comment]
Thanks for the reply :)

I've already contributed a few hardened systemd units to different projects like [1] and [2], so I think I won't have issues with that (hopefully!). My question was more about what the unit should be used for, as I don't fully understand how the devportal service behaves (e.g. the service should be a Type=simple one, right?).

I've been watching Accrescent for a while, and I'd really like to start helping from somewhere. So, sorry for my basic questions!

[1]: https://salsa.debian.org/lamby/pkg-redis/-/merge_requests/8

[2]: https://github.com/strukturag/nextcloud-spreed-signaling/pull/276

**Comment by lberrymage** [comment]
Oh okay. That's great!

The devportal is a Go web server which runs in the foreground and handles authentication for developers, accepts uploaded apps, and publishes them via the reposerver's REST API. It keeps track of state in `./devportal.db` and will create and delete temporary directories with pseudorandom names in `/` to hold apps which haven't yet been published (of course we don't want them to actually be created in `/` in production, so that should be changed. I'm not sure why I didn't set that up as a relative path in the first place).

reposerver is also a Go web server that runs in the foreground, and it accepts apps via a REST API from devportal and publishes them in a directory tree located at `PUBLISH_DIR` (would it be easier to harden the unit if this path was static?). A static web server then serves the files at `PUBLISH_DIR` to make them available to the client app.

Is any of that helpful?

I appreciate the willingness to contribute by the way! Hopefully this will all be easier to digest once documentation is added.

**Comment by Tachi107** [comment]
> The devportal is a Go web server which runs in the foreground and handles authentication for developers, accepts uploaded apps, and publishes them via the reposerver's REST API. It keeps track of state in `./devportal.db` and will create and delete temporary directories with pseudorandom names in `/` to hold apps which haven't yet been published (of course we don't want them to actually be created in `/` in production, so that should be changed. I'm not sure why I didn't set that up as a relative path in the first place).

Using relative paths doesn't generally work well with systemd units, as services are supposed to write to the various standard Unix directories (see [`file-hierarchy(7)`](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html)), but if you'd prefer not to make edits to the code it should be enough to set [`WorkingDirectory=`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=) to a subdirectory of `/var/local/` or `/var/lib/`.

As for the temporary files written to `/`, could you point me to the piece of code that manages them? I can change that to use `/tmp/` or `$TMPDIR`.

> reposerver is also a Go web server that runs in the foreground, and it accepts apps via a REST API from devportal and publishes them in a directory tree located at `PUBLISH_DIR` (would it be easier to harden the unit if this path was static?). A static web server then serves the files at `PUBLISH_DIR` to make them available to the client app.

Dynamic paths should be fine; we could set the env var in the systemd unit itself, so that it knows which directories should be available to the service. [`systemd.exec(5)`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment%20Variables%20in%20Spawned%20Processes) describes pretty well how env vars are handled in systemd units.

> Is any of that helpful?

Yep :)
 
> I appreciate the willingness to contribute by the way! Hopefully this will all be easier to digest once documentation is added.

Yeah, documentation would definitely make this easier

**Comment by lberrymage** [comment]
> Using relative paths doesn't generally work well with systemd units, as services are supposed to write to the various standard Unix directories (see [`file-hierarchy(7)`](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html)), but if you'd prefer not to make edits to the code it should be enough to set [`WorkingDirectory=`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=) to a subdirectory of `/var/local/` or `/var/lib/`.

I'd prefer to use a relative path in tandem with `WorkingDirectory=` unless there's a good reason to do otherwise. Although this software is intended to be run on a typical systemd-based Linux distribution, I think it would be good to avoid platform-specific code as much as possible.

> As for the temporary files written to `/`, could you point me to the piece of code that manages them? I can change that to use `/tmp/` or `$TMPDIR`.

[`new_app.go`](https://github.com/accrescent/devportal/blob/6c20ed2dc21b155f244c7a7ea21e3fd5194db0cf/devportal/api/new_app.go#L27-L61) and [`update_app.go`](https://github.com/accrescent/devportal/blob/6c20ed2dc21b155f244c7a7ea21e3fd5194db0cf/devportal/api/update_app.go#L43-L77) (and yes, this duplication and fragmentation of file management is... subpar. I'm currently refactoring the entire developer portal to handle this better among other many other things. It's not exactly at a production stage yet :) ). I'm not sure if `/tmp` is the best place to put the APK sets though - they may be saved for longer than the host's uptime if submitted to the review process.

> Dynamic paths should be fine; we could set the env var in the systemd unit itself, so that it knows which directories should be available to the service. [`systemd.exec(5)`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment%20Variables%20in%20Spawned%20Processes) describes pretty well how env vars are handled in systemd units.

Great.

**Comment by lberrymage** [comment]
As of https://github.com/accrescent/devportal/commit/1c839fadc55d7a919b86bcd91a071631011fab0c the file storage backend is generic and so can easily point to wherever we like.
